const sellingItems = [
    {
        id: 1,
        brand: 'Yamaha',
        title: 'Yamaha YZ450F',
        type: 'Dirtbike',
        color: 'Blue',
        ccm: 450,
        previousOwners: 3,
        hours: 23,
        description: 'Powerful motocross bike with responsive handling and lightweight chassis.',
        year: 2021,
        img1: '',
        img2: '',
        img3: '',
    },
    {
        id: 2,
        brand: 'KTM',
        title: 'KTM 250 SX-F',
        type: 'Dirtbike',
        color: 'Orange',
        ccm: 250,
        previousOwners: 1,
        hours: 15,
        description: 'Race-ready 4-stroke motocross machine with top-end performance.',
        year: 2022,
        img1: '',
        img2: '',
        img3: '',
    },
    {
        id: 3,
        brand: 'Can-Am',
        title: 'Can-Am Outlander 1000R',
        type: 'ATV',
        color: 'Yellow',
        ccm: 1000,
        previousOwners: 2,
        hours: 40,
        description: 'All-terrain vehicle with impressive torque and stability for offroad adventure.',
        year: 2020,
        img1: '',
        img2: '',
        img3: '',
    },
    {
        id: 4,
        brand: 'Polaris',
        title: 'Polaris Sportsman 570',
        type: 'ATV',
        color: 'Green',
        ccm: 570,
        previousOwners: 1,
        hours: 28,
        description: 'Reliable mid-size ATV perfect for trails and utility work.',
        year: 2023,
        img1: '',
        img2: '',
        img3: '',
    },
    {
        id: 5,
        brand: 'Ski-Doo',
        title: 'Ski-Doo MXZ X 850 E-TEC',
        type: 'Snowmobile',
        color: 'Black',
        ccm: 850,
        previousOwners: 0,
        hours: 10,
        description: 'High-performance snowmobile with quick throttle response and precise handling.',
        year: 2024,
        img1: '',
        img2: '',
        img3: '',
    },
    {
        id: 6,
        brand: 'Lynx',
        title: 'Lynx Rave RE 600R E-TEC',
        type: 'Snowmobile',
        color: 'Red',
        ccm: 600,
        previousOwners: 1,
        hours: 32,
        description: 'Trail-dominating snowmobile built for Scandinavian conditions.',
        year: 2021,
        img1: '',
        img2: '',
        img3: '',
    },
    {
        id: 7,
        brand: 'Sea-Doo',
        title: 'Sea-Doo RXP-X 300',
        type: 'Jetski',
        color: 'Yellow',
        ccm: 1630,
        previousOwners: 1,
        hours: 19,
        description: 'Performance watercraft built for speed and agility on open water.',
        year: 2022,
        img1: '',
        img2: '',
        img3: '',
    },
    {
        id: 8,
        brand: 'Yamaha',
        title: 'Yamaha FX Cruiser SVHO',
        type: 'Jetski',
        color: 'Blue',
        ccm: 1812,
        previousOwners: 0,
        hours: 12,
        description: 'Luxury watercraft with supercharged power and smooth ride.',
        year: 2023,
        img1: '',
        img2: '',
        img3: '',
    },
    {
        id: 9,
        brand: 'Can-Am',
        title: 'Can-Am Maverick X3 Turbo RR',
        type: 'Side-by-Side',
        color: 'Orange',
        ccm: 900,
        previousOwners: 2,
        hours: 45,
        description: 'Extreme off-road buggy with turbocharged power and advanced suspension.',
        year: 2021,
        img1: '',
        img2: '',
        img3: '',
    },
    {
        id: 10,
        brand: 'Polaris',
        title: 'Polaris RZR Pro R Ultimate',
        type: 'Side-by-Side',
        color: 'Gray',
        ccm: 2000,
        previousOwners: 1,
        hours: 30,
        description: 'High-output side-by-side with 225 HP and cutting-edge offroad control.',
        year: 2023,
        img1: '',
        img2: '',
        img3: '',
    },
    {
        id: 11,
        brand: 'Honda',
        title: 'Honda CRF450R',
        type: 'Dirtbike',
        color: 'Red',
        ccm: 450,
        previousOwners: 2,
        hours: 36,
        description: 'Aggressive motocross bike designed for track performance and control.',
        year: 2022,
        img1: '',
        img2: '',
        img3: '',
    },
    {
        id: 12,
        brand: 'Kawasaki',
        title: 'Kawasaki KX250',
        type: 'Dirtbike',
        color: 'Green',
        ccm: 250,
        previousOwners: 1,
        hours: 21,
        description: 'Lightweight motocross machine with smooth power delivery and sharp handling.',
        year: 2023,
        img1: '',
        img2: '',
        img3: '',
    },
    {
        id: 13,
        brand: 'Suzuki',
        title: 'Suzuki RM-Z450',
        type: 'Dirtbike',
        color: 'Yellow',
        ccm: 450,
        previousOwners: 3,
        hours: 47,
        description: 'Durable motocross bike with consistent throttle response and stability.',
        year: 2020,
        img1: '',
        img2: '',
        img3: '',
    },
    {
        id: 14,
        brand: 'CFMoto',
        title: 'CFMoto CForce 850XC',
        type: 'ATV',
        color: 'Black',
        ccm: 850,
        previousOwners: 2,
        hours: 38,
        description: 'High-powered ATV with modern design and smooth CVTech transmission.',
        year: 2021,
        img1: '',
        img2: '',
        img3: '',
    },
    {
        id: 15,
        brand: 'Yamaha',
        title: 'Yamaha Grizzly 700 EPS',
        type: 'ATV',
        color: 'Camo',
        ccm: 700,
        previousOwners: 1,
        hours: 24,
        description: 'Reliable utility ATV built for both work and trail fun.',
        year: 2023,
        img1: '',
        img2: '',
        img3: '',
    },
    {
        id: 16,
        brand: 'Arctic Cat',
        title: 'Arctic Cat M 8000 Mountain Cat',
        type: 'Snowmobile',
        color: 'Black/Green',
        ccm: 800,
        previousOwners: 1,
        hours: 18,
        description: 'Deep snow beast with lightweight platform and powerful 800cc 2-stroke engine.',
        year: 2022,
        img1: '',
        img2: '',
        img3: '',
    },
    {
        id: 17,
        brand: 'Yamaha',
        title: 'Yamaha Sidewinder L-TX LE',
        type: 'Snowmobile',
        color: 'Blue',
        ccm: 998,
        previousOwners: 0,
        hours: 12,
        description: 'Turbocharged snowmobile delivering unmatched top speed and acceleration.',
        year: 2024,
        img1: '',
        img2: '',
        img3: '',
    },
    {
        id: 18,
        brand: 'Polaris',
        title: 'Polaris Indy 650 XC',
        type: 'Snowmobile',
        color: 'Red/Black',
        ccm: 650,
        previousOwners: 2,
        hours: 34,
        description: 'Trail-focused snowmobile known for its comfort and reliability.',
        year: 2021,
        img1: '',
        img2: '',
        img3: '',
    },
    {
        id: 19,
        brand: 'Sea-Doo',
        title: 'Sea-Doo GTX Limited 300',
        type: 'Jetski',
        color: 'Gray',
        ccm: 1630,
        previousOwners: 1,
        hours: 25,
        description: 'Luxury touring watercraft with high comfort, speed, and iBR braking system.',
        year: 2023,
        img1: '',
        img2: '',
        img3: '',
    },
    {
        id: 20,
        brand: 'Kawasaki',
        title: 'Kawasaki Ultra 310LX',
        type: 'Jetski',
        color: 'Black/Green',
        ccm: 1498,
        previousOwners: 0,
        hours: 9,
        description: 'Supercharged personal watercraft delivering 310 horsepower and smooth ride.',
        year: 2024,
        img1: '',
        img2: '',
        img3: '',
    },
    {
        id: 21,
        brand: 'Can-Am',
        title: 'Can-Am Defender HD10',
        type: 'Side-by-Side',
        color: 'Mossy Oak',
        ccm: 976,
        previousOwners: 1,
        hours: 52,
        description: 'Utility-focused side-by-side built for farm and forest terrain.',
        year: 2021,
        img1: '',
        img2: '',
        img3: '',
    },
    {
        id: 22,
        brand: 'CFMoto',
        title: 'CFMoto ZForce 1000 Sport',
        type: 'Side-by-Side',
        color: 'Gray/Orange',
        ccm: 963,
        previousOwners: 1,
        hours: 27,
        description: 'Stylish and agile side-by-side with excellent suspension and comfort.',
        year: 2022,
        img1: '',
        img2: '',
        img3: '',
    },
    {
        id: 23,
        brand: 'Polaris',
        title: 'Polaris General XP 1000 Deluxe',
        type: 'Side-by-Side',
        color: 'Black',
        ccm: 999,
        previousOwners: 2,
        hours: 42,
        description: 'Adventure-ready side-by-side combining utility strength and offroad fun.',
        year: 2020,
        img1: '',
        img2: '',
        img3: '',
    },
    {
        id: 24,
        brand: 'Yamaha',
        title: 'Yamaha Wolverine RMAX2 1000',
        type: 'Side-by-Side',
        color: 'Blue',
        ccm: 999,
        previousOwners: 0,
        hours: 19,
        description: 'Premium side-by-side with adaptive suspension and powerful twin engine.',
        year: 2023,
        img1: '',
        img2: '',
        img3: '',
    },
    {
        id: 25,
        brand: 'Segway',
        title: 'Segway Snarler AT6 L',
        type: 'ATV',
        color: 'Gray/Red',
        ccm: 570,
        previousOwners: 1,
        hours: 22,
        description: 'Modern ATV with digital display, EPS steering, and reliable 570cc engine.',
        year: 2022,
        img1: '',
        img2: '',
        img3: '',
    },
];

export default sellingItems;
